# Generated by Django 5.1.1 on 2024-09-12 10:36

import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('updated_at', models.DateTimeField(verbose_name='updated at')),
                ('id', models.CharField(max_length=27, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('added_by', models.CharField(max_length=27)),
                ('category', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('updated_at', models.DateTimeField(verbose_name='updated at')),
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False, unique=True)),
                ('proposed_return_date', models.DateTimeField()),
                ('is_returned', models.BooleanField(default=False)),
                ('borrower', models.CharField(db_index=True, max_length=27)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='borrowing_records', to='books.book'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
