# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pagekeeper/protos/pagekeeper.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, '', 'pagekeeper/protos/pagekeeper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n"pagekeeper/protos/pagekeeper.proto\x12\npagekeeper"Z\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08is_admin\x18\x03 \x01(\x08\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x12\n\nfirst_name\x18\x05 \x01(\t"k\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x10\n\x08is_admin\x18\x05 \x01(\x08"/\n\x10RegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t"6\n\x13\x41uthenticateRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t"]\n\x14\x41uthenticateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x1e\n\x04user\x18\x03 \x01(\x0b\x32\x10.pagekeeper.User"%\n\rVerifyRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t"A\n\x0eVerifyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1e\n\x04user\x18\x02 \x01(\x0b\x32\x10.pagekeeper.User"A\n\x11\x46\x65tchUsersRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x0b\n\x03ids\x18\x03 \x03(\t"q\n\x12\x46\x65tchUsersResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0btotal_users\x18\x02 \x01(\x05\x12\x14\n\x0c\x63urrent_page\x18\x03 \x01(\x05\x12\x1f\n\x05users\x18\x04 \x03(\x0b\x32\x10.pagekeeper.User2\xbc\x02\n\nPageKeeper\x12G\n\x08Register\x12\x1b.pagekeeper.RegisterRequest\x1a\x1c.pagekeeper.RegisterResponse"\x00\x12S\n\x0c\x41uthenticate\x12\x1f.pagekeeper.AuthenticateRequest\x1a .pagekeeper.AuthenticateResponse"\x00\x12\x41\n\x06Verify\x12\x19.pagekeeper.VerifyRequest\x1a\x1a.pagekeeper.VerifyResponse"\x00\x12M\n\nFetchUsers\x12\x1d.pagekeeper.FetchUsersRequest\x1a\x1e.pagekeeper.FetchUsersResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pagekeeper.protos.pagekeeper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_USER']._serialized_start = 50
    _globals['_USER']._serialized_end = 140
    _globals['_REGISTERREQUEST']._serialized_start = 142
    _globals['_REGISTERREQUEST']._serialized_end = 249
    _globals['_REGISTERRESPONSE']._serialized_start = 251
    _globals['_REGISTERRESPONSE']._serialized_end = 298
    _globals['_AUTHENTICATEREQUEST']._serialized_start = 300
    _globals['_AUTHENTICATEREQUEST']._serialized_end = 354
    _globals['_AUTHENTICATERESPONSE']._serialized_start = 356
    _globals['_AUTHENTICATERESPONSE']._serialized_end = 449
    _globals['_VERIFYREQUEST']._serialized_start = 451
    _globals['_VERIFYREQUEST']._serialized_end = 488
    _globals['_VERIFYRESPONSE']._serialized_start = 490
    _globals['_VERIFYRESPONSE']._serialized_end = 555
    _globals['_FETCHUSERSREQUEST']._serialized_start = 557
    _globals['_FETCHUSERSREQUEST']._serialized_end = 622
    _globals['_FETCHUSERSRESPONSE']._serialized_start = 624
    _globals['_FETCHUSERSRESPONSE']._serialized_end = 737
    _globals['_PAGEKEEPER']._serialized_start = 740
    _globals['_PAGEKEEPER']._serialized_end = 1056
# @@protoc_insertion_point(module_scope)
