name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PAGEKEEPER_MONGODB_URL: mongodb://localhost:27017
  LIBRARIAN_DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
  BOOKWORM_DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
  LIBRARIAN_RABBITMQ_URL: amqp://guest:guest@localhost:5672/
  BOOKWORM_RABBITMQ_URL: amqp://guest:guest@localhost:5672/

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      mongodb:
        image: mongo:jammy
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync -p 3.12

      - name: Lint
        run: make lint

      - name: Run test suite for Librarian
        run: make test-librarian

      - name: Run test suite for Pagekeeper
        run: make test-pagekeeper

      - name: Run test suite for Bookworm
        run: make test-bookworm
